CREATE TABLE IF NOT EXISTS USERS (
	ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NAME CHARACTER VARYING(100) NOT NULL,
	EMAIL CHARACTER VARYING
);

CREATE TABLE IF NOT EXISTS ITEMS (
	ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	NAME CHARACTER VARYING(100) NOT NULL,
	DESCRIPTION CHARACTER VARYING,
	AVAILABLE BOOLEAN,
	ID BIGINT OWNER REFERENCES USERS (ID) ON DELETE CASCADE,
	ID BIGINT REQUEST
);
